development:
  adapter: mysql2
  encoding: utf8
  database: ti3_randomizer_development
  pool: 5
  username: root
  password:
#test:
#  adapter: mysql2
#  encoding: utf8
#  database: scorekeeper_test
#  pool: 5
#  username: root
#  password:
#production:
#  adapter: mysql2
#  encoding: utf8
#  database: scorekeeper_production
#  pool: 5
#  username: root
#  password: